# Generated by Django 2.2.3 on 2019-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_photo',
            field=models.ImageField(blank=True, upload_to='system_photos', verbose_name='system-logo'),
        ),
    ]
